/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuItemInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const CartItem = IDL.Record({
  'quantity' : IDL.Nat,
  'menuItemId' : IDL.Nat,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addMenuItem' : IDL.Func([MenuItemInput], [IDL.Nat], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'clearCart' : IDL.Func([], [], []),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getOrderStatus' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'placeOrder' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'setMenuItemAvailability' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuItemInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const CartItem = IDL.Record({ 'quantity' : IDL.Nat, 'menuItemId' : IDL.Nat });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addMenuItem' : IDL.Func([MenuItemInput], [IDL.Nat], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'clearCart' : IDL.Func([], [], []),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getOrderStatus' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'placeOrder' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'setMenuItemAvailability' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };